language: php

cache: bundler

php:
  - 5.4
  - 5.5

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com
    - curl -L https://www.opscode.com/chef/install.sh | sudo bash
    - gem install librarian-chef
    - librarian-chef install
    - echo "cookbook_path [ \"/home/travis/build/Kunstmaan/skylab/cookbooks\" ]" > solo.rb
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    - sudo a2enmod rewrite actions fastcgi alias version
    - sudo service mysql stop
    - sudo rm -Rf /var/lib/mysql/
    - sudo chef-solo --log_level debug -c solo.rb -o "applications::packagemanager,git::default,skylab::postgresql,applications::mysql,skylab::apache,skylab::directories"

script:
    - ./compile --version 0.0.0
    - php skylab.phar new test -vvv --no-interaction
    - php skylab.phar apply test symfony -vvv --no-interaction
    - php skylab.phar maintenance -vvv --no-interaction
    - php skylab.phar remove test --force -vvv --no-interaction
    - ./skylab new test -vvv --no-interaction
    - ./skylab apply test symfony -vvv --no-interaction
    - ./skylab maintenance -vvv --no-interaction
    - ./skylab remove test --force -vvv --no-interaction
    - php skylab.phar new test -vvv --no-interaction
    - php skylab.phar apply test smartcms -vvv --no-interaction
    - php skylab.phar maintenance -vvv --no-interaction
    - php skylab.phar remove test --force -vvv --no-interaction
    - ./skylab new test -vvv --no-interaction
    - ./skylab apply test smartcms -vvv --no-interaction
    - ./skylab maintenance -vvv --no-interaction
    - ./skylab remove test --force -vvv --no-interaction
    - php skylab.phar self-update --no-interaction

