language: php

php:
  - 5.4
  - 5.5

before_script:
    - sudo mkdir -p /home/projects
    - sudo mkdir -p /home/backupped-projects
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --dev --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script:
    - ./compile --version v0.0.0-travis
    - php skylab.phar self-update
    - ./skylab new test -vvv
    - ./skylab maintenance -vvv
    - ./skylab remove test --force -vvv