language: php

php:
  - 5.4
  - 5.5

before_script:
    - sudo mkdir -p /home/projects
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --dev --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script:
    - ./skylab
    - ./skylab maintenance
    - ./skylab new test
    - ./skylab maintenance