projects:
    path:       "/home/projects"
    backuppath: "/home/backupped-projects"

users:
    superuser:      root
    supergroup:     root
    wwwuser:        _www
    postgresuser:   postgres

apache:
    admin:        support@kunstmaan.be
    vhostdir:     /etc/apache2/conf/projects.d
    hostmachine:  dev.kunstmaan.be

awstats:
    password: password

permissions:
    develmode:  false

mysql:
    password: password

postgresql:
    user: skylab
    password: password

skeletons:
    base:       Kunstmaan\Skylab\Skeleton\BaseSkeleton
    mysql:      Kunstmaan\Skylab\Skeleton\MySQLSkeleton
    apache:     Kunstmaan\Skylab\Skeleton\ApacheSkeleton
    php5:       Kunstmaan\Skylab\Skeleton\PHPSkeleton
    symfony:    Kunstmaan\Skylab\Skeleton\SymfonySkeleton
    awstats:    Kunstmaan\Skylab\Skeleton\AwstatsSkeleton
    anacron:    Kunstmaan\Skylab\Skeleton\AnacronSkeleton
    fcron:      false
    logrotate:  Kunstmaan\Skylab\Skeleton\LogrotateSkeleton
    nagios:     false
    mon:        false
    pingdom:    Kunstmaan\Skylab\Skeleton\PingdomSkeleton
    postgres:   Kunstmaan\Skylab\Skeleton\PostgreSQLSkeleton
    tomcat:     Kunstmaan\Skylab\Skeleton\TomcatSkeleton
    smartcms:   Kunstmaan\Skylab\Skeleton\JavaSkeleton

debug: true
